### ISSUE TITLE
Noticing this after an order is fulfilled - KeyError: 'order_id'

### ISSUE THREAD

**Issue by THREELabs** [rhettre/coinbase-advancedtrade-python#92]
Issue:
Order fulfills it looks like, but seeing the following error. Noticed today.

Testing with sample script:
client.fiat_limit_buy("DOGE-USD", "1")

Error:
site-packages/coinbase_advanced_trader/services/order_service.py", line 201, in _place_limit_order
    id=order_response['order_id'],
KeyError: 'order_id'

**Comment by bjgpp** [comment]
I started getting the same error message on 9/4.  Was running flawlessly every day for over a month in AWS Lambda.  

Sample Script:
client.fiat_limit_buy("BTC-USD", "30")
client.fiat_limit_buy("ETH-USD", "10")
client.fiat_limit_buy("SOL-USD", "10")

BTC Order gets placed on Coinbase, then I receive the below error.  The ETH and SOL orders don't end up getting placed due to the error.

Lambda Response Error:
 "errorMessage": "'order_id'",
  "errorType": "KeyError",

**Comment by rhettre** [comment]
Saw this in the Coinbase AT Discord (Coinbase changed their schema and broke everyone). This guy reported a fix (see below). Merged pull request to fix this in release 0.2.5

Chuy — 09/03/2024 11:53 AM
I had some nasty prod outage today due to coinbase API changes:

Posting to  "/api/v3/brokerage/orders" previously returned:
{'success': True, 'failure_reason': 'UNKNOWN_FAILURE_REASON', 'order_id': '168..', 'success_response': {'order_id': '168...


After 30 minutes ago, the "top" order_id was removed from the API respinses:
{'success': True, 'success_response': {'order_id': '4


Patched on my side and sharing here in case anyone else was relying on that response['order_id'] which is now response['success_response']['order_id']

**Comment by THREELabs** [comment]
Thanks for the update I gotta hop on that discord

**Comment by yizzyyikes** [comment]
Thanks for the update.  It appears v0.2.5 didn't fix my issue, however I was able to use your feedback and changed 3 lines within the order_service.py file and everything is working again.

Original
`id=order_response['order_id'],`

Revised
`id=order_response['success_response']['order_id'],`

**Comment by rhettre** [comment]
Looks like the lambda layer that got generated pulled 0.2.4 instead of 0.2.5 - I just fixed it thanks for pointing that out.

0.2.5 should have those three changes in order_service.py that you're talking about (diff here: https://github.com/rhettre/coinbase-advancedtrade-python/pull/93/commits/1dbbaede779ad01628e0020b51b1778264461bbe)
